image:https://img.shields.io/github/license/lazy-cat-io/tenet[license,link=license]
image:https://img.shields.io/github/v/release/lazy-cat-io/tenet.svg[https://github.com/lazy-cat-io/tenet/releases]
image:https://img.shields.io/clojars/v/io.lazy-cat/tenet.svg[clojars,link=https://clojars.org/io.lazy-cat/tenet]

image:https://codecov.io/gh/lazy-cat-io/tenet/branch/master/graph/badge.svg?token=BGGNUI43Y2[codecov,https://codecov.io/gh/lazy-cat-io/tenet]
image:https://github.com/lazy-cat-io/tenet/actions/workflows/build.yml/badge.svg[build,https://github.com/lazy-cat-io/tenet/actions/workflows/build.yml]
image:https://github.com/lazy-cat-io/tenet/actions/workflows/deploy.yml/badge.svg[deploy,https://github.com/lazy-cat-io/tenet/actions/workflows/deploy.yml]

== io.lazy-cat/tenet

A Clojure(Script) library, which helps to create explicit and understandable results to unify and simplify the data flow.

=== Rationale

==== Problem statement

Usually, when working in a team, it is necessary to agree beforehand on the type of results to be used.
Someone uses maps, someone uses vectors, someone uses monads like `Either`, `Maybe`, etc.

It is not always clear when a function returns data without some context (e.g. `nil`, `42`, etc).

What does `nil` mean: No data?
Didn't do anything?
Did something go wrong?

What does `42` mean: User id?
Age?

Such answers make you look at the current implementation and spend time understanding the current context.

Imagine that we have a function containing some kind of business logic:

[source,clojure]
----
(defn create-user! [user]
  (if-not (valid? user)
    ;; returns the response that the data is not valid
    (if-not (exists? user)
      ;; returns the response that the email is occupied
      (db/insert! user)))) ;; returns the response that the user was created or an error occurred while writing data to the database
----

In this case, there may be several possible responses:

- the user data is not valid
- the email is occupied
- an error occurred while writing data to the database
- or finally, a response about a successful operation: e.g. user id or data

There is a useful data type in the Clojure - a `keyword` that can be used to add some context to the response:

- `:user/incorrect`, `:user/exists`
- `:user/created` or `:org.acme.user/created`

Having such an answer, it is immediately clear what exactly happened - we have the context and data.
Most of the time we do not write code, we read it.
And this is very important.

We have decided on the context, but how to add it?
Key-value in the map?
Vector?
Monad?
Metadata?
And how to understand which answer is considered an error (anomaly)?

We used all the above methods in our practice, and it has always been something inconvenient.

What should be the structure of the map, vector?
Create custom object/type and use getters and setters?
This adds problems in further use and looks like OOP.
Use metadata?
Metadata cannot be added to some types of data.
And what type of response is considered an error?

==== Solution

TBD

See the performance link:src/bench/clojure/perf.clj[tests].

=== Getting started

Add the following dependency in your project:

.project.clj or build.boot
[source,clojure]
----
[io.lazy-cat/tenet "2.0.0"]
----

.deps.edn or bb.edn
[source,clojure]
----
io.lazy-cat/tenet {:mvn/version "2.0.0"}
----

=== Limitations

TBD

=== API

TBD

=== License

link:license[Copyright © 2022-2024 lazy-cat.io]
